//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class category
    {
        public int id { get; set; }
        
        public string title { get; set; }
       
        public string description { get; set; }

        [Display (Name = "Date Added")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{DD/MM/yyyy}")]
        public DateTime? dateAdded { get; set; }

        // public Nullable<System.DateTime> dateAdded { get; set; }

        public int addedBy { get; set; }
        
        public virtual User User { get; set; }
    }
}
