//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class customer
    {
        public int id { get; set; }
        
        public string name { get; set; }
       
        public string type { get; set; }
       
        public string emailAddress { get; set; }
       
        public string contact { get; set; }
      
        public string address { get; set; }

       
        public DateTime? addedDate { get; set; }

       
        public int addedBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
