//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public string type { get; set; }
        public Nullable<int> dealer_cust_id { get; set; }
        public Nullable<decimal> grandTotal { get; set; }
        public Nullable<System.DateTime> transactionDate { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> discount { get; set; }
        public int addedBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
